[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "filelock>=3.19.1",
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "pandas>=2.3.2",
    "requests>=2.32.5",
    "waitress>=3.0.2",
]
